---

- name: install podman
  dnf:
    name: podman
    state: latest
  become: true

- name: install git
  dnf:
    name: git
    state: latest
  become: true

- name: ensure group tweakstreet exists
  group:
    name: tweakstreet
    state: present
    gid: 101
  become: true

- name: ensure user tweakstreet exists
  user:
    name: tweakstreet
    comment: Tweakstreet User
    uid: 101
    group: tweakstreet
  become: true

- name: change ownership of /opt folder
  file:
    path: /opt
    state: directory
    recurse: no
    owner: root
    group: uwe
    mode: '0775'
  become: yes

...
